# Generated by Django 3.2.16 on 2022-11-19 15:24

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0004_alter_poetry_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='股票名称', max_length=20)),
                ('code', models.CharField(help_text='股票代码', max_length=20)),
                ('date_time', models.DateTimeField(help_text='股票代码', verbose_name='股票日期')),
                ('open_price', models.FloatField(default=0.0, help_text='开盘价格')),
                ('new_price', models.FloatField(default=0.0, help_text='收盘价格')),
                ('top_price', models.FloatField(default=0.0, help_text='最高价格')),
                ('down_price', models.FloatField(default=0.0, help_text='最低价格')),
                ('turnover', models.IntegerField(default=0, help_text='成交量')),
                ('business_volume', models.IntegerField(default=0, help_text='成交额')),
                ('amplitude', models.FloatField(default=0.0, help_text='振幅')),
                ('rise_and_fall', models.FloatField(default=0.0, help_text='涨跌幅')),
                ('rise_and_price', models.FloatField(default=0.0, help_text='涨跌额')),
                ('turnover_rate', models.FloatField(default=0.0, help_text='换手率')),
                ('is_delete', models.BooleanField(default=0.0, help_text='是否删除')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存时间')),
            ],
            options={
                'db_table': 'shares',
            },
        ),
    ]
