# Generated by Django 3.2.16 on 2022-11-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0007_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='end_time',
            field=models.DateTimeField(help_text='截止时间', null=True, verbose_name='截止时间'),
        ),
    ]
