# Generated by Django 3.2.16 on 2022-11-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0008_todo_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_done',
            field=models.BooleanField(default=False, help_text='是否完成'),
        ),
    ]
