# Generated by Django 3.2.16 on 2022-11-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0009_todo_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='is_done',
            field=models.IntegerField(default=0, help_text='是否完成'),
        ),
    ]
