# Generated by Django 3.2.16 on 2022-11-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0010_alter_todo_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_home',
            field=models.BooleanField(default=False, help_text='是否展示到首页'),
        ),
    ]
