# Generated by Django 3.2.16 on 2022-11-23 18:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0011_todo_is_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharesHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='持仓股票名称', max_length=20)),
                ('code', models.CharField(help_text='持仓股票代码', max_length=20)),
                ('number', models.IntegerField(default=0, help_text='持仓数量')),
                ('cost_price', models.FloatField(default=0.0, help_text='成本价')),
                ('is_delete', models.BooleanField(default=False, help_text='是否删除')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存时间')),
            ],
            options={
                'db_table': 'shares_hold',
            },
        ),
        migrations.AlterField(
            model_name='shares',
            name='code',
            field=models.CharField(default=None, help_text='股票代码', max_length=20),
        ),
        migrations.AlterField(
            model_name='shares',
            name='name',
            field=models.CharField(default=None, help_text='股票名称', max_length=20),
        ),
        migrations.AddField(
            model_name='shares',
            name='shares_hold',
            field=models.ForeignKey(default='', help_text='持仓股票ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='nb.shareshold'),
        ),
    ]
