# Generated by Django 3.2.16 on 2022-11-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0013_shareshold_profit_and_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='shares',
            name='color',
            field=models.CharField(default='green', help_text='折线颜色', max_length=20, null=True),
        ),
    ]
