# Generated by Django 3.2.16 on 2022-11-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0014_shares_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shares',
            name='color',
        ),
        migrations.AddField(
            model_name='shareshold',
            name='color',
            field=models.CharField(default='green', help_text='折线颜色', max_length=20, null=True),
        ),
    ]
