# Generated by Django 3.2.16 on 2022-11-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0015_auto_20221124_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareshold',
            name='last_close_price',
            field=models.FloatField(default=0.0, help_text='上一天收盘价', null=True),
        ),
        migrations.AddField(
            model_name='shareshold',
            name='today_price',
            field=models.FloatField(default=0.0, help_text='当天盈亏', null=True),
        ),
    ]
