# Generated by Django 3.2.16 on 2022-11-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0017_auto_20221127_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareshold',
            name='last_day',
            field=models.DateTimeField(help_text='上一天日期', null=True, verbose_name='上一天日期'),
        ),
    ]
