# Generated by Django 3.2.16 on 2022-11-28 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0019_stockdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdetail',
            name='shares_hold',
            field=models.ForeignKey(default='', help_text='持仓股票ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='nb.shareshold'),
        ),
    ]
