# Generated by Django 3.2.16 on 2022-11-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0020_stockdetail_shares_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareshold',
            name='is_detail',
            field=models.BooleanField(default=False, help_text='是否查看详情'),
        ),
    ]
