# Generated by Django 3.2.16 on 2022-11-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0021_shareshold_is_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetail',
            name='date',
            field=models.DateTimeField(help_text='日期', null=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='time',
            field=models.DateTimeField(help_text='时间', null=True, verbose_name='时间'),
        ),
    ]
