# Generated by Django 3.2.16 on 2022-11-28 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0022_auto_20221128_2247'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stockdetail',
            table='stockDetail',
        ),
    ]
