# Generated by Django 3.2.16 on 2022-11-28 22:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0023_alter_stockdetail_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdetail',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存时间'),
        ),
        migrations.AddField(
            model_name='stockdetail',
            name='is_delete',
            field=models.BooleanField(default=False, help_text='是否删除'),
        ),
        migrations.AddField(
            model_name='stockdetail',
            name='update_date',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间'),
        ),
    ]
