# Generated by Django 3.2.16 on 2022-11-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0024_auto_20221128_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetail',
            name='buyFive',
            field=models.IntegerField(default=0, help_text='买五'),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='buyFour',
            field=models.IntegerField(default=0, help_text='买四'),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='buyOne',
            field=models.IntegerField(default=0, help_text='买一'),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='buyThree',
            field=models.IntegerField(default=0, help_text='买三'),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='buyTwo',
            field=models.IntegerField(default=0, help_text='买二'),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='sellFive',
            field=models.IntegerField(default=0, help_text='卖五'),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='sellFour',
            field=models.IntegerField(default=0, help_text='卖四'),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='sellOne',
            field=models.IntegerField(default=0, help_text='卖一'),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='sellThree',
            field=models.IntegerField(default=0, help_text='卖三'),
        ),
        migrations.AlterField(
            model_name='stockdetail',
            name='sellTwo',
            field=models.IntegerField(default=0, help_text='卖二'),
        ),
    ]
