# Generated by Django 3.2.16 on 2022-11-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0025_auto_20221128_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareshold',
            name='days',
            field=models.IntegerField(default=0, help_text='持仓天数'),
        ),
    ]
