# Generated by Django 3.2.16 on 2022-12-01 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0027_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date',
        ),
    ]
