# Generated by Django 3.2.16 on 2022-12-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0030_alter_shareshold_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='obj_id',
            field=models.CharField(help_text='对象ID', max_length=50, null=True),
        ),
    ]
