# Generated by Django 3.2.16 on 2022-12-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0032_kdjstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='kdjstock',
            name='t',
            field=models.DateTimeField(help_text='时间', null=True, verbose_name='时间'),
        ),
    ]
