# Generated by Django 3.2.16 on 2022-12-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0033_kdjstock_t'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareshold',
            name='down_price',
            field=models.FloatField(default=0.0, help_text='今日跌停价', null=True),
        ),
        migrations.AddField(
            model_name='shareshold',
            name='top_price',
            field=models.FloatField(default=0.0, help_text='今日涨停价', null=True),
        ),
    ]
