# Generated by Django 3.2.16 on 2022-12-14 20:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0034_auto_20221214_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdetail',
            name='avg_price',
            field=models.FloatField(default=0.0, help_text='平均价'),
        ),
        migrations.AddField(
            model_name='stockdetail',
            name='down_price',
            field=models.FloatField(default=0.0, help_text='跌停价'),
        ),
        migrations.AddField(
            model_name='stockdetail',
            name='top_price',
            field=models.FloatField(default=0.0, help_text='涨停价'),
        ),
        migrations.AddField(
            model_name='stockdetail',
            name='turnover_rate',
            field=models.FloatField(default=0.0, help_text='换手率'),
        ),
        migrations.CreateModel(
            name='StockSector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, help_text='股票名称', max_length=20)),
                ('code', models.CharField(default=None, help_text='股票代码', max_length=20)),
                ('sector_code', models.CharField(default=None, help_text='板块代码', max_length=20)),
                ('sector_name', models.CharField(default=None, help_text='板块名称', max_length=20)),
                ('sector_rate', models.FloatField(default=0.0, help_text='板块涨幅')),
                ('is_delete', models.BooleanField(default=False, help_text='是否删除')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存时间')),
                ('shares_hold', models.ForeignKey(default='', help_text='持仓股票ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='nb.shareshold')),
            ],
            options={
                'db_table': 'stock_sector',
            },
        ),
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, help_text='股票名称', max_length=20)),
                ('code', models.CharField(default=None, help_text='股票代码', max_length=20)),
                ('time', models.DateTimeField(help_text='信息更新时间', null=True, verbose_name='信息更新时间')),
                ('holder_code', models.CharField(default=None, help_text='股东代码', max_length=50)),
                ('holder_name', models.CharField(default=None, help_text='股东代码', max_length=200)),
                ('hold_number', models.CharField(default=None, help_text='持股数', max_length=50)),
                ('hold_rate', models.CharField(default=None, help_text='持股比例', max_length=50)),
                ('fluctuate', models.CharField(default=None, help_text='增减', max_length=50)),
                ('fluctuate_rate', models.CharField(default=None, help_text='变动率', max_length=50)),
                ('is_delete', models.BooleanField(default=False, help_text='是否删除')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存时间')),
                ('shares_hold', models.ForeignKey(default='', help_text='持仓股票ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='nb.shareshold')),
            ],
            options={
                'db_table': 'shareholder',
            },
        ),
        migrations.CreateModel(
            name='InflowStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, help_text='股票名称', max_length=20)),
                ('code', models.CharField(default=None, help_text='股票代码', max_length=20)),
                ('time', models.DateTimeField(help_text='时间', null=True, verbose_name='时间')),
                ('main_inflow', models.IntegerField(default=0, help_text='主力净流入')),
                ('small_inflow', models.IntegerField(default=0, help_text='小单净流入')),
                ('middle_inflow', models.IntegerField(default=0, help_text='中单净流入')),
                ('big_inflow', models.IntegerField(default=0, help_text='大单净流入')),
                ('huge_inflow', models.IntegerField(default=0, help_text='超大单净流入')),
                ('is_delete', models.BooleanField(default=False, help_text='是否删除')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存时间')),
                ('shares_hold', models.ForeignKey(default='', help_text='持仓股票ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='nb.shareshold')),
            ],
            options={
                'db_table': 'inflow_stock',
            },
        ),
    ]
