# Generated by Django 3.2.16 on 2022-12-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0035_auto_20221214_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflowstock',
            name='big_inflow',
            field=models.FloatField(default=0.0, help_text='大单净流入'),
        ),
        migrations.AlterField(
            model_name='inflowstock',
            name='huge_inflow',
            field=models.FloatField(default=0.0, help_text='超大单净流入'),
        ),
        migrations.AlterField(
            model_name='inflowstock',
            name='main_inflow',
            field=models.FloatField(default=0.0, help_text='主力净流入'),
        ),
        migrations.AlterField(
            model_name='inflowstock',
            name='middle_inflow',
            field=models.FloatField(default=0.0, help_text='中单净流入'),
        ),
        migrations.AlterField(
            model_name='inflowstock',
            name='small_inflow',
            field=models.FloatField(default=0.0, help_text='小单净流入'),
        ),
    ]
