# Generated by Django 3.2.16 on 2022-12-14 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0036_auto_20221214_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdetail',
            name='competitivePri',
        ),
        migrations.RemoveField(
            model_name='stockdetail',
            name='dot',
        ),
        migrations.RemoveField(
            model_name='stockdetail',
            name='nowPic',
        ),
        migrations.RemoveField(
            model_name='stockdetail',
            name='nowTraAmount',
        ),
        migrations.RemoveField(
            model_name='stockdetail',
            name='nowTraNumber',
        ),
        migrations.RemoveField(
            model_name='stockdetail',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='stockdetail',
            name='reservePri',
        ),
    ]
