# Generated by Django 3.2.16 on 2022-12-14 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0037_auto_20221214_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdetail',
            name='date',
        ),
        migrations.RemoveField(
            model_name='stockdetail',
            name='dayurl',
        ),
        migrations.RemoveField(
            model_name='stockdetail',
            name='minurl',
        ),
        migrations.RemoveField(
            model_name='stockdetail',
            name='monthurl',
        ),
        migrations.RemoveField(
            model_name='stockdetail',
            name='weekurl',
        ),
    ]
