# Generated by Django 3.2.16 on 2022-12-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0038_auto_20221214_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdetail',
            name='date',
            field=models.DateTimeField(help_text='日期', null=True, verbose_name='日期'),
        ),
    ]
