# Generated by Django 3.2.16 on 2022-12-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0041_inflowstock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholder',
            name='hold_rate',
            field=models.FloatField(default=0.0, help_text='持股比例'),
        ),
        migrations.AlterField(
            model_name='shareholder',
            name='holder_name',
            field=models.CharField(default=None, help_text='股东名称', max_length=200),
        ),
    ]
