# Generated by Django 3.2.16 on 2022-12-16 16:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0043_message_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSuper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, help_text='股票名称', max_length=20)),
                ('code', models.CharField(default=None, help_text='股票代码', max_length=20)),
                ('time', models.DateTimeField(help_text='上榜日期', null=True, verbose_name='上榜日期')),
                ('unscramble', models.CharField(default=None, help_text='解读', max_length=200)),
                ('open_price', models.FloatField(default=0.0, help_text='收盘价')),
                ('rise_rate', models.FloatField(default=0.0, help_text='涨跌幅')),
                ('turnover_rate', models.FloatField(default=0.0, help_text='换手率')),
                ('net_purchase_amount', models.FloatField(default=0.0, help_text='龙虎榜净买额')),
                ('purchase_amount', models.FloatField(default=0.0, help_text='龙虎榜买入额')),
                ('sales_amount', models.FloatField(default=0.0, help_text='龙虎榜卖出额')),
                ('turnover_amount', models.FloatField(default=0.0, help_text='龙虎榜成交额')),
                ('total_turnover_amount', models.FloatField(default=0.0, help_text='市场总成交额')),
                ('net_purchases_rate', models.FloatField(default=0.0, help_text='净买额占总成交比')),
                ('net_turnover_rate', models.FloatField(default=0.0, help_text='成交额占总成交比')),
                ('market_equity', models.FloatField(default=0.0, help_text='流通市值')),
                ('reason', models.CharField(default=None, help_text='上榜原因', max_length=200)),
            ],
            options={
                'db_table': 'stock_super',
            },
        ),
        migrations.CreateModel(
            name='ShareholderNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, help_text='股票名称', max_length=20)),
                ('code', models.CharField(default=None, help_text='股票代码', max_length=20)),
                ('holder_number', models.FloatField(default=0.0, help_text='股东人数')),
                ('fluctuate', models.FloatField(default=0.0, help_text='股东人数增减')),
                ('diff_rate', models.FloatField(default=0.0, help_text='较上期变化百分比')),
                ('end_time', models.DateTimeField(help_text='股东户数统计截止日', null=True, verbose_name='股东户数统计截止日')),
                ('avg_amount', models.FloatField(default=0.0, help_text='户均持股市值')),
                ('avg_number', models.FloatField(default=0.0, help_text='户均持股数量')),
                ('total_amount', models.FloatField(default=0.0, help_text='总市值')),
                ('total_price', models.FloatField(default=0.0, help_text='总股本')),
                ('notice_date', models.DateTimeField(help_text='公告日期', null=True, verbose_name='公告日期')),
                ('is_delete', models.BooleanField(default=False, help_text='是否删除')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存时间')),
                ('shares_hold', models.ForeignKey(default='', help_text='持仓股票ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='nb.shareshold')),
            ],
            options={
                'db_table': 'shareholder_number',
            },
        ),
    ]
