# Generated by Django 3.2.16 on 2022-12-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0045_auto_20221216_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdetail',
            name='P_E_ratio_dynamic',
            field=models.FloatField(default=0.0, help_text='市盈率(动)'),
        ),
        migrations.AddField(
            model_name='stockdetail',
            name='ROE_ratio',
            field=models.FloatField(default=0.0, help_text='净资产收益率'),
        ),
        migrations.AddField(
            model_name='stockdetail',
            name='circulation_market_value',
            field=models.FloatField(default=0.0, help_text='流通市值'),
        ),
        migrations.AddField(
            model_name='stockdetail',
            name='gross_profit_margin',
            field=models.FloatField(default=0.0, help_text='毛利率'),
        ),
        migrations.AddField(
            model_name='stockdetail',
            name='industry',
            field=models.CharField(default=None, help_text='所处行业', max_length=20),
        ),
        migrations.AddField(
            model_name='stockdetail',
            name='net_interest_rate',
            field=models.FloatField(default=0.0, help_text='净利率'),
        ),
        migrations.AddField(
            model_name='stockdetail',
            name='net_profit',
            field=models.FloatField(default=0.0, help_text='净利润'),
        ),
        migrations.AddField(
            model_name='stockdetail',
            name='section_no',
            field=models.CharField(default=None, help_text='板块编号', max_length=20),
        ),
        migrations.AddField(
            model_name='stockdetail',
            name='total_market_value',
            field=models.FloatField(default=0.0, help_text='总市值'),
        ),
    ]
