# Generated by Django 3.2.16 on 2022-12-19 15:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0046_auto_20221219_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTodayPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='持仓股票名称', max_length=20)),
                ('code', models.CharField(help_text='持仓股票代码', max_length=20)),
                ('today_price', models.FloatField(default=0.0, help_text='当天盈亏', null=True)),
                ('is_delete', models.BooleanField(default=False, help_text='是否删除')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存时间')),
                ('shares_hold', models.ForeignKey(default='', help_text='持仓股票ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='nb.shareshold')),
            ],
            options={
                'db_table': 'stock_today_price',
            },
        ),
        migrations.CreateModel(
            name='StockChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='持仓股票名称', max_length=20)),
                ('code', models.CharField(help_text='持仓股票代码', max_length=20)),
                ('number', models.IntegerField(default=0, help_text='持仓数量')),
                ('cost_price', models.FloatField(default=0.0, help_text='成本价')),
                ('change_date', models.DateTimeField(help_text='变更时间', null=True, verbose_name='变更时间')),
                ('is_delete', models.BooleanField(default=False, help_text='是否删除')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存时间')),
                ('shares_hold', models.ForeignKey(default='', help_text='持仓股票ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='nb.shareshold')),
            ],
            options={
                'db_table': 'stock_change',
            },
        ),
    ]
