# Generated by Django 3.2.16 on 2022-12-20 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0047_stockchange_stocktodayprice'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stockdetail',
            table='stock_detail',
        ),
    ]
