# Generated by Django 3.2.16 on 2023-01-02 13:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0050_shareshold_buy_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, help_text='股票名称', max_length=20)),
                ('code', models.CharField(default=None, help_text='股票代码', max_length=20)),
                ('time', models.DateTimeField(help_text='时间', null=True, verbose_name='时间')),
                ('old_price', models.FloatField(default=0.0, help_text='昨收')),
                ('deal_price', models.FloatField(default=0.0, help_text='成交价')),
                ('deal_number', models.IntegerField(default=0, help_text='成交量')),
                ('singular', models.IntegerField(default=0, help_text='单数')),
                ('is_delete', models.BooleanField(default=False, help_text='是否删除')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存时间')),
                ('shares_hold', models.ForeignKey(default='', help_text='持仓股票ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='nb.shareshold')),
            ],
            options={
                'db_table': 'stock_deal',
            },
        ),
    ]
