# Generated by Django 3.2.16 on 2023-01-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0055_rename_kdjstock_stockkdj'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockkdj',
            name='time',
            field=models.DateTimeField(auto_now=True, help_text='时间', verbose_name='时间'),
        ),
    ]
