# Generated by Django 3.2.16 on 2023-01-04 15:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0057_auto_20230103_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMACD',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dif', models.FloatField(default=0.0, help_text='dif值')),
                ('dea', models.FloatField(default=0.0, help_text='dea值')),
                ('macd', models.FloatField(default=0.0, help_text='macd值')),
                ('time', models.DateTimeField(help_text='时间', null=True, verbose_name='时间')),
                ('name', models.CharField(help_text='股票名称', max_length=20)),
                ('type', models.CharField(help_text='金叉-死叉', max_length=20)),
                ('is_delete', models.BooleanField(default=False, help_text='是否删除')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存时间')),
                ('shares_hold', models.ForeignKey(default='', help_text='持仓股票ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='nb.shareshold')),
            ],
            options={
                'db_table': 'stock_macd',
            },
        ),
    ]
