# Generated by Django 3.2.16 on 2023-01-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nb', '0059_stockrsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrsi',
            name='close',
            field=models.FloatField(default=0.0, help_text='收盘价'),
        ),
    ]
